export const EMOJIS: { id: string; name: string }[] = [
  { id: '😀', name: 'grinning' },
  { id: '😃', name: 'smiley' },
  { id: '😄', name: 'smile' },
  { id: '😁', name: 'grin' },
  { id: '😆', name: 'laughing' },
  { id: '😅', name: 'sweat smile' },
  { id: '🤣', name: 'rofl' },
  { id: '😂', name: 'joy' },
  { id: '🙂', name: 'slightly smiling' },
  { id: '😉', name: 'wink' },
  { id: '😊', name: 'blush' },
  { id: '😇', name: 'innocent' },
  { id: '🥰', name: 'smiling hearts' },
  { id: '😍', name: 'heart eyes' },
  { id: '🤩', name: 'star struck' },
  { id: '😘', name: 'kiss' },
  { id: '😋', name: 'yum' },
  { id: '😛', name: 'stuck out tongue' },
  { id: '😜', name: 'wink tongue' },
  { id: '🤪', name: 'zany' },
  { id: '🤗', name: 'hug' },
  { id: '🤭', name: 'hand over mouth' },
  { id: '🤫', name: 'shush' },
  { id: '🤔', name: 'thinking' },
  { id: '🫡', name: 'salute' },
  { id: '🤐', name: 'zipper mouth' },
  { id: '🤨', name: 'raised eyebrow' },
  { id: '😐', name: 'neutral' },
  { id: '😑', name: 'expressionless' },
  { id: '😶', name: 'no mouth' },
  { id: '😏', name: 'smirk' },
  { id: '😒', name: 'unamused' },
  { id: '🙄', name: 'eye roll' },
  { id: '😬', name: 'grimace' },
  { id: '😌', name: 'relieved' },
  { id: '😔', name: 'pensive' },
  { id: '😪', name: 'sleepy' },
  { id: '🤤', name: 'drool' },
  { id: '😴', name: 'sleep' },
  { id: '😷', name: 'mask' },
  { id: '🤒', name: 'sick' },
  { id: '🤕', name: 'injured' },
  { id: '🤢', name: 'nauseated' },
  { id: '🤮', name: 'vomit' },
  { id: '🥴', name: 'woozy' },
  { id: '😵', name: 'dizzy' },
  { id: '🤯', name: 'exploding head' },
  { id: '🤠', name: 'cowboy' },
  { id: '🥳', name: 'party' },
  { id: '😎', name: 'cool' },
  { id: '🤓', name: 'nerd' },
  { id: '🧐', name: 'monocle' },
  { id: '😕', name: 'confused' },
  { id: '😟', name: 'worried' },
  { id: '🙁', name: 'slight frown' },
  { id: '😮', name: 'open mouth' },
  { id: '😯', name: 'hushed' },
  { id: '😲', name: 'astonished' },
  { id: '😳', name: 'flushed' },
  { id: '🥺', name: 'pleading' },
  { id: '😦', name: 'frowning' },
  { id: '😨', name: 'fearful' },
  { id: '😰', name: 'anxious' },
  { id: '😥', name: 'sad relieved' },
  { id: '😢', name: 'cry' },
  { id: '😭', name: 'sob' },
  { id: '😱', name: 'scream' },
  { id: '😖', name: 'confounded' },
  { id: '😣', name: 'persevere' },
  { id: '😞', name: 'disappointed' },
  { id: '😓', name: 'sweat' },
  { id: '😩', name: 'weary' },
  { id: '😫', name: 'tired' },
  { id: '🥱', name: 'yawn' },
  { id: '😤', name: 'triumph' },
  { id: '😡', name: 'pout' },
  { id: '😠', name: 'angry' },
  { id: '🤬', name: 'cursing' },
  { id: '😈', name: 'smiling devil' },
  { id: '👿', name: 'angry devil' },
  { id: '💀', name: 'skull' },
  { id: '☠️', name: 'skull crossbones' },
  { id: '💩', name: 'poop' },
  { id: '🤡', name: 'clown' },
  { id: '👹', name: 'ogre' },
  { id: '👺', name: 'goblin' },
  { id: '👻', name: 'ghost' },
  { id: '👽', name: 'alien' },
  { id: '👾', name: 'alien monster' },
  { id: '🤖', name: 'robot' },
  { id: '🎃', name: 'pumpkin' },
  { id: '😺', name: 'smiley cat' },
  { id: '😸', name: 'smile cat' },
  { id: '😹', name: 'joy cat' },
  { id: '😻', name: 'heart eyes cat' },
  { id: '😼', name: 'smirk cat' },
  { id: '😽', name: 'kiss cat' },
  { id: '🙀', name: 'scream cat' },
  { id: '😿', name: 'cry cat' },
  { id: '😾', name: 'pout cat' },
  { id: '🙈', name: 'see no evil' },
  { id: '🙉', name: 'hear no evil' },
  { id: '🙊', name: 'speak no evil' },
  { id: '👋', name: 'wave' },
  { id: '🤚', name: 'raised back of hand' },
  { id: '🖐️', name: 'hand' },
  { id: '✋', name: 'raised hand' },
  { id: '🖖', name: 'vulcan' },
  { id: '👌', name: 'ok' },
  { id: '🤌', name: 'pinched fingers' },
  { id: '🤏', name: 'pinch' },
  { id: '✌️', name: 'victory' },
  { id: '🤞', name: 'crossed fingers' },
  { id: '🤟', name: 'love you' },
  { id: '🤘', name: 'horns' },
  { id: '🤙', name: 'call me' },
  { id: '👈', name: 'point left' },
  { id: '👉', name: 'point right' },
  { id: '👆', name: 'point up' },
  { id: '👇', name: 'point down' },
  { id: '☝️', name: 'index up' },
  { id: '👍', name: 'thumbs up' },
  { id: '👎', name: 'thumbs down' },
  { id: '✊', name: 'fist' },
  { id: '👊', name: 'punch' },
  { id: '🤛', name: 'left fist' },
  { id: '🤜', name: 'right fist' },
  { id: '👏', name: 'clap' },
  { id: '🙌', name: 'raised hands' },
  { id: '🫶', name: 'heart hands' },
  { id: '👐', name: 'open hands' },
  { id: '🤲', name: 'palms up' },
  { id: '🤝', name: 'handshake' },
  { id: '🙏', name: 'pray' },
  { id: '✍️', name: 'writing' },
  { id: '💅', name: 'nail polish' },
  { id: '🤳', name: 'selfie' },
  { id: '💪', name: 'muscle' },
  { id: '🦾', name: 'mechanical arm' },
  { id: '🦵', name: 'leg' },
  { id: '🦶', name: 'foot' },
  { id: '👂', name: 'ear' },
  { id: '👃', name: 'nose' },
  { id: '👀', name: 'eyes' },
  { id: '👁️', name: 'eye' },
  { id: '👅', name: 'tongue' },
  { id: '👄', name: 'mouth' },
  { id: '💋', name: 'kiss mark' },
  { id: '💘', name: 'heart arrow' },
  { id: '💝', name: 'heart ribbon' },
  { id: '💖', name: 'sparkling heart' },
  { id: '💗', name: 'growing heart' },
  { id: '💓', name: 'beating heart' },
  { id: '💞', name: 'revolving hearts' },
  { id: '💕', name: 'two hearts' },
  { id: '💟', name: 'heart decoration' },
  { id: '❣️', name: 'heart exclamation' },
  { id: '💔', name: 'broken heart' },
  { id: '❤️', name: 'red heart' },
  { id: '🧡', name: 'orange heart' },
  { id: '💛', name: 'yellow heart' },
  { id: '💚', name: 'green heart' },
  { id: '💙', name: 'blue heart' },
  { id: '💜', name: 'purple heart' },
  { id: '🖤', name: 'black heart' },
  { id: '🤍', name: 'white heart' },
  { id: '🤎', name: 'brown heart' },
  { id: '💯', name: 'hundred' },
  { id: '💢', name: 'anger' },
  { id: '💥', name: 'boom' },
  { id: '💫', name: 'dizzy star' },
  { id: '💦', name: 'sweat drops' },
  { id: '💨', name: 'dash' },
  { id: '💬', name: 'speech balloon' },
  { id: '💭', name: 'thought balloon' },
  { id: '💤', name: 'zzz' },
  { id: '👋', name: 'wave hand' },
  { id: '🔥', name: 'fire' },
  { id: '✨', name: 'sparkles' },
  { id: '⭐', name: 'star' },
  { id: '🌟', name: 'glowing star' },
  { id: '⚡', name: 'zap' },
  { id: '☀️', name: 'sun' },
  { id: '🌙', name: 'moon' },
  { id: '🌈', name: 'rainbow' },
  { id: '☁️', name: 'cloud' },
  { id: '❄️', name: 'snowflake' },
  { id: '💧', name: 'droplet' },
  { id: '🌊', name: 'wave' },
  { id: '🌸', name: 'cherry blossom' },
  { id: '🌹', name: 'rose' },
  { id: '🌺', name: 'hibiscus' },
  { id: '🌻', name: 'sunflower' },
  { id: '🌼', name: 'blossom' },
  { id: '🌷', name: 'tulip' },
  { id: '🌱', name: 'seedling' },
  { id: '🌲', name: 'evergreen' },
  { id: '🌳', name: 'tree' },
  { id: '🌴', name: 'palm' },
  { id: '🌵', name: 'cactus' },
  { id: '🍀', name: 'four leaf clover' },
  { id: '🍁', name: 'maple' },
  { id: '🍄', name: 'mushroom' },
  { id: '🍇', name: 'grapes' },
  { id: '🍉', name: 'watermelon' },
  { id: '🍊', name: 'orange' },
  { id: '🍋', name: 'lemon' },
  { id: '🍌', name: 'banana' },
  { id: '🍍', name: 'pineapple' },
  { id: '🍎', name: 'red apple' },
  { id: '🍏', name: 'green apple' },
  { id: '🍑', name: 'peach' },
  { id: '🍒', name: 'cherries' },
  { id: '🍓', name: 'strawberry' },
  { id: '🥝', name: 'kiwi' },
  { id: '🍅', name: 'tomato' },
  { id: '🥑', name: 'avocado' },
  { id: '🍆', name: 'eggplant' },
  { id: '🌽', name: 'corn' },
  { id: '🌶️', name: 'chili' },
  { id: '🥕', name: 'carrot' },
  { id: '🧄', name: 'garlic' },
  { id: '🧅', name: 'onion' },
  { id: '🍞', name: 'bread' },
  { id: '🧀', name: 'cheese' },
  { id: '🍔', name: 'burger' },
  { id: '🍟', name: 'fries' },
  { id: '🍕', name: 'pizza' },
  { id: '🌭', name: 'hotdog' },
  { id: '🥪', name: 'sandwich' },
  { id: '🌮', name: 'taco' },
  { id: '🍣', name: 'sushi' },
  { id: '🍱', name: 'bento' },
  { id: '🍜', name: 'ramen' },
  { id: '🍝', name: 'spaghetti' },
  { id: '🍲', name: 'stew' },
  { id: '🍦', name: 'ice cream' },
  { id: '🍩', name: 'doughnut' },
  { id: '🍪', name: 'cookie' },
  { id: '🎂', name: 'cake' },
  { id: '🧁', name: 'cupcake' },
  { id: '🍫', name: 'chocolate' },
  { id: '🍬', name: 'candy' },
  { id: '🍭', name: 'lollipop' },
  { id: '☕', name: 'coffee' },
  { id: '🍵', name: 'tea' },
  { id: '🧃', name: 'juice' },
  { id: '🥤', name: 'cup straw' },
  { id: '🍺', name: 'beer' },
  { id: '🍻', name: 'cheers' },
  { id: '🍷', name: 'wine' },
  { id: '🥂', name: 'champagne' },
  { id: '🍸', name: 'cocktail' },
  { id: '🧋', name: 'boba' },
  { id: '🐶', name: 'dog' },
  { id: '🐱', name: 'cat' },
  { id: '🐭', name: 'mouse' },
  { id: '🐹', name: 'hamster' },
  { id: '🐰', name: 'rabbit' },
  { id: '🦊', name: 'fox' },
  { id: '🐻', name: 'bear' },
  { id: '🐼', name: 'panda' },
  { id: '🐨', name: 'koala' },
  { id: '🐯', name: 'tiger' },
  { id: '🦁', name: 'lion' },
  { id: '🐮', name: 'cow' },
  { id: '🐷', name: 'pig' },
  { id: '🐸', name: 'frog' },
  { id: '🐵', name: 'monkey' },
  { id: '🐔', name: 'chicken' },
  { id: '🐧', name: 'penguin' },
  { id: '🐦', name: 'bird' },
  { id: '🐤', name: 'chick' },
  { id: '🦆', name: 'duck' },
  { id: '🦉', name: 'owl' },
  { id: '🦇', name: 'bat' },
  { id: '🐺', name: 'wolf' },
  { id: '🐗', name: 'boar' },
  { id: '🐴', name: 'horse' },
  { id: '🦄', name: 'unicorn' },
  { id: '🐝', name: 'bee' },
  { id: '🐛', name: 'bug' },
  { id: '🦋', name: 'butterfly' },
  { id: '🐌', name: 'snail' },
  { id: '🐞', name: 'ladybug' },
  { id: '🐢', name: 'turtle' },
  { id: '🐍', name: 'snake' },
  { id: '🦎', name: 'lizard' },
  { id: '🐙', name: 'octopus' },
  { id: '🦑', name: 'squid' },
  { id: '🦐', name: 'shrimp' },
  { id: '🦞', name: 'lobster' },
  { id: '🦀', name: 'crab' },
  { id: '🐡', name: 'blowfish' },
  { id: '🐠', name: 'tropical fish' },
  { id: '🐟', name: 'fish' },
  { id: '🐬', name: 'dolphin' },
  { id: '🐳', name: 'whale' },
  { id: '🦈', name: 'shark' },
  { id: '🐊', name: 'crocodile' },
  { id: '🐘', name: 'elephant' },
  { id: '🦒', name: 'giraffe' },
  { id: '🦘', name: 'kangaroo' },
  { id: '🐫', name: 'camel' },
  { id: '🦙', name: 'llama' },
  { id: '🦌', name: 'deer' },
  { id: '🐕', name: 'dog face' },
  { id: '🐈', name: 'cat face' },
  { id: '🐓', name: 'rooster' },
  { id: '🦃', name: 'turkey' },
  { id: '🦚', name: 'peacock' },
  { id: '🦜', name: 'parrot' },
  { id: '🦢', name: 'swan' },
  { id: '🦩', name: 'flamingo' },
  { id: '🕊️', name: 'dove' },
  { id: '🐇', name: 'rabbit face' },
  { id: '🦝', name: 'raccoon' },
  { id: '🦨', name: 'skunk' },
  { id: '🦡', name: 'badger' },
  { id: '🦦', name: 'otter' },
  { id: '🦥', name: 'sloth' },
  { id: '🐁', name: 'mouse face' },
  { id: '🐀', name: 'rat' },
  { id: '🦔', name: 'hedgehog' },
  { id: '🐾', name: 'paw prints' },
  { id: '🚗', name: 'car' },
  { id: '🚕', name: 'taxi' },
  { id: '🚌', name: 'bus' },
  { id: '🏎️', name: 'race car' },
  { id: '🚓', name: 'police car' },
  { id: '🚑', name: 'ambulance' },
  { id: '🚒', name: 'fire engine' },
  { id: '🚜', name: 'tractor' },
  { id: '🛵', name: 'scooter' },
  { id: '🚲', name: 'bike' },
  { id: '🚂', name: 'locomotive' },
  { id: '✈️', name: 'airplane' },
  { id: '🚀', name: 'rocket' },
  { id: '🛸', name: 'ufo' },
  { id: '🚁', name: 'helicopter' },
  { id: '⛵', name: 'sailboat' },
  { id: '🚢', name: 'ship' },
  { id: '🏠', name: 'house' },
  { id: '🏡', name: 'house garden' },
  { id: '🏢', name: 'office' },
  { id: '🏬', name: 'department store' },
  { id: '🏭', name: 'factory' },
  { id: '🏰', name: 'castle' },
  { id: '🗼', name: 'tower' },
  { id: '🗽', name: 'statue of liberty' },
  { id: '⛪', name: 'church' },
  { id: '⛺', name: 'tent' },
  { id: '🌁', name: 'foggy' },
  { id: '🌃', name: 'night' },
  { id: '🌄', name: 'sunrise mountain' },
  { id: '🌅', name: 'sunrise' },
  { id: '🌆', name: 'dusk' },
  { id: '🌇', name: 'sunset' },
  { id: '🌉', name: 'bridge' },
  { id: '🎠', name: 'carousel' },
  { id: '🎡', name: 'ferris wheel' },
  { id: '🎢', name: 'roller coaster' },
  { id: '💈', name: 'barber' },
  { id: '🎪', name: 'circus' },
  { id: '🎨', name: 'art' },
  { id: '🎬', name: 'clapper' },
  { id: '🎤', name: 'mic' },
  { id: '🎧', name: 'headphones' },
  { id: '🎼', name: 'score' },
  { id: '🎹', name: 'piano' },
  { id: '🥁', name: 'drum' },
  { id: '🎷', name: 'saxophone' },
  { id: '🎺', name: 'trumpet' },
  { id: '🎸', name: 'guitar' },
  { id: '🪕', name: 'banjo' },
  { id: '🎻', name: 'violin' },
  { id: '🎲', name: 'dice' },
  { id: '♟️', name: 'chess' },
  { id: '🎯', name: 'bullseye' },
  { id: '🎳', name: 'bowling' },
  { id: '🎮', name: 'video game' },
  { id: '🕹️', name: 'joystick' },
  { id: '🎰', name: 'slot' },
  { id: '🧩', name: 'puzzle' },
  { id: '🧸', name: 'teddy' },
  { id: '🖼️', name: 'frame' },
  { id: '💡', name: 'bulb' },
  { id: '🔦', name: 'flashlight' },
  { id: '🏮', name: 'lantern' },
  { id: '📔', name: 'notebook' },
  { id: '📕', name: 'closed book' },
  { id: '📖', name: 'open book' },
  { id: '📗', name: 'green book' },
  { id: '📘', name: 'blue book' },
  { id: '📙', name: 'orange book' },
  { id: '📚', name: 'books' },
  { id: '📓', name: 'notebook' },
  { id: '📃', name: 'page' },
  { id: '📜', name: 'scroll' },
  { id: '📄', name: 'document' },
  { id: '📰', name: 'newspaper' },
  { id: '📑', name: 'bookmark tabs' },
  { id: '🔖', name: 'bookmark' },
  { id: '🏷️', name: 'label' },
  { id: '💰', name: 'money bag' },
  { id: '💴', name: 'yen' },
  { id: '💵', name: 'dollar' },
  { id: '💶', name: 'euro' },
  { id: '💷', name: 'pound' },
  { id: '💸', name: 'money with wings' },
  { id: '💳', name: 'card' },
  { id: '💎', name: 'gem' },
  { id: '⚖️', name: 'balance' },
  { id: '🧰', name: 'toolbox' },
  { id: '🔧', name: 'wrench' },
  { id: '🔨', name: 'hammer' },
  { id: '⚙️', name: 'gear' },
  { id: '🔗', name: 'link' },
  { id: '📎', name: 'paperclip' },
  { id: '✂️', name: 'scissors' },
  { id: '📐', name: 'triangle ruler' },
  { id: '📏', name: 'ruler' },
  { id: '📌', name: 'pin' },
  { id: '📍', name: 'round pin' },
  { id: '🔒', name: 'lock' },
  { id: '🔓', name: 'unlock' },
  { id: '🔑', name: 'key' },
  { id: '🗝️', name: 'old key' },
  { id: '🔨', name: 'hammer tool' },
  { id: '🛡️', name: 'shield' },
  { id: '🧲', name: 'magnet' },
  { id: '🧪', name: 'test tube' },
  { id: '🧫', name: 'petri' },
  { id: '🧬', name: 'dna' },
  { id: '🔬', name: 'microscope' },
  { id: '🔭', name: 'telescope' },
  { id: '📡', name: 'satellite' },
  { id: '💉', name: 'syringe' },
  { id: '💊', name: 'pill' },
  { id: '🩹', name: 'bandage' },
  { id: '🩺', name: 'stethoscope' },
  { id: '🚪', name: 'door' },
  { id: '🛏️', name: 'bed' },
  { id: '🛋️', name: 'couch' },
  { id: '🚽', name: 'toilet' },
  { id: '🚿', name: 'shower' },
  { id: '🛁', name: 'bath' },
  { id: '🧴', name: 'lotion' },
  { id: '🧹', name: 'broom' },
  { id: '🧺', name: 'basket' },
  { id: '🧻', name: 'roll' },
  { id: '🧼', name: 'soap' },
  { id: '🧽', name: 'sponge' },
  { id: '🧯', name: 'extinguisher' },
  { id: '🛒', name: 'cart' },
  { id: '🚬', name: 'cigarette' },
  { id: '⚰️', name: 'coffin' },
  { id: '🪦', name: 'headstone' },
  { id: '🗿', name: 'moai' },
  { id: '🧿', name: 'nazar' },
  { id: '🔮', name: 'crystal ball' },
  { id: '🧸', name: 'teddy bear' },
  { id: '🧵', name: 'thread' },
  { id: '🧶', name: 'yarn' },
  { id: '👓', name: 'glasses' },
  { id: '🕶️', name: 'sunglasses' },
  { id: '🥽', name: 'goggles' },
  { id: '🥼', name: 'lab coat' },
  { id: '🦺', name: 'safety vest' },
  { id: '👔', name: 'necktie' },
  { id: '👕', name: 'shirt' },
  { id: '👖', name: 'jeans' },
  { id: '🧣', name: 'scarf' },
  { id: '🧤', name: 'gloves' },
  { id: '🧥', name: 'coat' },
  { id: '🧦', name: 'socks' },
  { id: '👗', name: 'dress' },
  { id: '👘', name: 'kimono' },
  { id: '👙', name: 'bikini' },
  { id: '👚', name: 'blouse' },
  { id: '👛', name: 'purse' },
  { id: '👜', name: 'handbag' },
  { id: '👝', name: 'pouch' },
  { id: '🎒', name: 'backpack' },
  { id: '👞', name: 'shoe' },
  { id: '👟', name: 'sneaker' },
  { id: '🥾', name: 'hiking boot' },
  { id: '🥿', name: 'flat shoe' },
  { id: '👠', name: 'heel' },
  { id: '👡', name: 'sandal' },
  { id: '👢', name: 'boot' },
  { id: '👑', name: 'crown' },
  { id: '👒', name: 'hat' },
  { id: '🎩', name: 'top hat' },
  { id: '🎓', name: 'graduation' },
  { id: '🧢', name: 'billed cap' },
  { id: '⛑️', name: 'rescue helmet' },
  { id: '📿', name: 'prayer beads' },
  { id: '💄', name: 'lipstick' },
  { id: '💍', name: 'ring' },
  { id: '💼', name: 'briefcase' },
  { id: '💻', name: 'laptop' },
  { id: '🖥️', name: 'desktop' },
  { id: '🖨️', name: 'printer' },
  { id: '⌨️', name: 'keyboard' },
  { id: '🖱️', name: 'mouse' },
  { id: '💽', name: 'minidisc' },
  { id: '💾', name: 'floppy' },
  { id: '💿', name: 'cd' },
  { id: '📀', name: 'dvd' },
  { id: '🎥', name: 'movie camera' },
  { id: '📷', name: 'camera' },
  { id: '📸', name: 'camera flash' },
  { id: '📹', name: 'video camera' },
  { id: '📼', name: 'vhs' },
  { id: '🔍', name: 'search left' },
  { id: '🔎', name: 'search right' },
  { id: '🕯️', name: 'candle' },
  { id: '📱', name: 'phone' },
  { id: '📲', name: 'phone arrow' },
  { id: '☎️', name: 'telephone' },
  { id: '📞', name: 'receiver' },
  { id: '📟', name: 'pager' },
  { id: '📠', name: 'fax' },
  { id: '🔋', name: 'battery' },
  { id: '🔌', name: 'plug' },
  { id: '💻', name: 'computer' },
  { id: '🧭', name: 'compass' },
  { id: '⏱️', name: 'stopwatch' },
  { id: '⏲️', name: 'timer' },
  { id: '⏰', name: 'alarm' },
  { id: '🕰️', name: 'mantelpiece' },
  { id: '⌛', name: 'hourglass' },
  { id: '⏳', name: 'hourglass flowing' },
  { id: '📡', name: 'antenna' },
  { id: '💎', name: 'diamond' },
  { id: '⚖️', name: 'scales' },
  { id: '🔧', name: 'spanner' },
  { id: '⚗️', name: 'alembic' },
  { id: '🧿', name: 'evil eye' },
  { id: '🧿', name: 'amulet' },
  { id: '🎵', name: 'note' },
  { id: '🎶', name: 'notes' },
  { id: '🔔', name: 'bell' },
  { id: '🔕', name: 'bell off' },
  { id: '📣', name: 'megaphone' },
  { id: '📢', name: 'loudspeaker' },
  { id: '💬', name: 'speech' },
  { id: '💭', name: 'thought' },
  { id: '♠️', name: 'spades' },
  { id: '♥️', name: 'hearts' },
  { id: '♦️', name: 'diamonds' },
  { id: '♣️', name: 'clubs' },
  { id: '🃏', name: 'joker' },
  { id: '🀄', name: 'mahjong' },
  { id: '🎴', name: 'flower cards' },
  { id: '🎭', name: 'performing arts' },
  { id: '🖼️', name: 'picture' },
  { id: '🎨', name: 'palette' },
  { id: '🧵', name: 'string' },
  { id: '🔖', name: 'bookmark mark' },
  { id: '🏷️', name: 'tag' },
  { id: '✅', name: 'check' },
  { id: '❌', name: 'cross' },
  { id: '❓', name: 'question' },
  { id: '❗', name: 'exclamation' },
  { id: '⭕', name: 'circle' },
  { id: '🔴', name: 'red circle' },
  { id: '🟠', name: 'orange circle' },
  { id: '🟡', name: 'yellow circle' },
  { id: '🟢', name: 'green circle' },
  { id: '🔵', name: 'blue circle' },
  { id: '🟣', name: 'purple circle' },
  { id: '⚫', name: 'black circle' },
  { id: '⚪', name: 'white circle' },
  { id: '⬛', name: 'black square' },
  { id: '⬜', name: 'white square' },
  { id: '🔶', name: 'orange diamond' },
  { id: '🔷', name: 'blue diamond' },
  { id: '💠', name: 'diamond dot' },
  { id: '🏁', name: 'chequered flag' },
  { id: '🚩', name: 'triangular flag' },
  { id: '🎌', name: 'crossed flags' },
  { id: '🏴', name: 'black flag' },
  { id: '🏳️', name: 'white flag' },
  { id: '🏳️‍🌈', name: 'rainbow flag' },
  { id: '🏴‍☠️', name: 'pirate flag' },
]
